In [1]:
import duckdb
import pandas as pd

In [2]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [3]:
con.execute("SELECT * FROM bronze_z0019")

In [4]:
df = con.execute("SELECT * FROM bronze_z0019").fetchdf()

In [5]:
df.head(50)

    NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0   10004     SERRA  BT50   100   200      z0019_2 2026-04-30 06:03:23.786959
1   10005   MACHADO  BT50   100   100      z0019_2 2026-04-30 06:03:23.786959
2   10003     PREGO  BT12   100    60      z0019_2 2026-04-30 06:03:23.786959
3   10004     SERRA  BT50   100   200      z0019_2 2026-04-30 06:03:23.786959
4   10005   MACHADO  BT50   100   100      z0019_2 2026-04-30 06:03:23.786959
5   10003     PREGO  BT12   100    60      z0019_2 2026-04-30 06:03:23.786959
6   10004     SERRA  BT50   100   200      z0019_2 2026-04-30 06:04:56.726600
7   10005   MACHADO  BT50   100   100      z0019_2 2026-04-30 06:04:56.726600
8   10003     PREGO  BT12   100    60      z0019_2 2026-04-30 06:04:56.726600
9   10004     SERRA  BT50   100   200      z0019_2 2026-04-30 06:04:56.726600
10  10005   MACHADO  BT50   100   100      z0019_2 2026-04-30 06:04:56.726600
11  10003     PREGO  BT12   100    60      z0019_2 2026-04-30 06:04:56.726600
12  10004     SERRA  BT50   100   200      z0019_2 2026-04-30 06:09:20.125918
13  10005   MACHADO  BT50   100   100      z0019_2 2026-04-30 06:09:20.125918
14  10003     PREGO  BT12   100    60      z0019_2 2026-04-30 06:09:20.125918
15  10004     SERRA  BT50   100   200      z0019_2 2026-04-30 06:13:30.850271
16  10005   MACHADO  BT50   100   100      z0019_2 2026-04-30 06:13:30.850271
17  10003     PREGO  BT12   100    60      z0019_2 2026-04-30 06:13:30.850271
18  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-04-30 06:16:34.351304
19  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-04-30 06:16:34.351304
20  10003     PREGO  BT10   100    50  z0019_1.csv 2026-04-30 06:16:34.351304
21  10004     SERRA  BT50   100   200  z0019_2.csv 2026-04-30 06:17:23.532040
22  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-04-30 06:17:23.532040
23  10003     PREGO  BT12   100    60  z0019_2.csv 2026-04-30 06:17:23.532040

In [6]:
df.duplicated().sum()

np.int64(6)

In [7]:
duplicados = df.duplicated()

In [8]:
linhas_duplicadas = df[duplicados]

In [9]:
linhas_duplicadas.head(50)

    NATBR    MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
3   10004    SERRA  BT50   100   200      z0019_2 2026-04-30 06:03:23.786959
4   10005  MACHADO  BT50   100   100      z0019_2 2026-04-30 06:03:23.786959
5   10003    PREGO  BT12   100    60      z0019_2 2026-04-30 06:03:23.786959
9   10004    SERRA  BT50   100   200      z0019_2 2026-04-30 06:04:56.726600
10  10005  MACHADO  BT50   100   100      z0019_2 2026-04-30 06:04:56.726600
11  10003    PREGO  BT12   100    60      z0019_2 2026-04-30 06:04:56.726600

In [10]:
df = df.drop_duplicates()
df.head(50)

    NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0   10004     SERRA  BT50   100   200      z0019_2 2026-04-30 06:03:23.786959
1   10005   MACHADO  BT50   100   100      z0019_2 2026-04-30 06:03:23.786959
2   10003     PREGO  BT12   100    60      z0019_2 2026-04-30 06:03:23.786959
6   10004     SERRA  BT50   100   200      z0019_2 2026-04-30 06:04:56.726600
7   10005   MACHADO  BT50   100   100      z0019_2 2026-04-30 06:04:56.726600
8   10003     PREGO  BT12   100    60      z0019_2 2026-04-30 06:04:56.726600
12  10004     SERRA  BT50   100   200      z0019_2 2026-04-30 06:09:20.125918
13  10005   MACHADO  BT50   100   100      z0019_2 2026-04-30 06:09:20.125918
14  10003     PREGO  BT12   100    60      z0019_2 2026-04-30 06:09:20.125918
15  10004     SERRA  BT50   100   200      z0019_2 2026-04-30 06:13:30.850271
16  10005   MACHADO  BT50   100   100      z0019_2 2026-04-30 06:13:30.850271
17  10003     PREGO  BT12   100    60      z0019_2 2026-04-30 06:13:30.850271
18  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-04-30 06:16:34.351304
19  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-04-30 06:16:34.351304
20  10003     PREGO  BT10   100    50  z0019_1.csv 2026-04-30 06:16:34.351304
21  10004     SERRA  BT50   100   200  z0019_2.csv 2026-04-30 06:17:23.532040
22  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-04-30 06:17:23.532040
23  10003     PREGO  BT12   100    60  z0019_2.csv 2026-04-30 06:17:23.532040

In [11]:
df.duplicated() .sum()

np.int64(0)

In [12]:
df.head(10)

    NATBR    MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0   10004    SERRA  BT50   100   200      z0019_2 2026-04-30 06:03:23.786959
1   10005  MACHADO  BT50   100   100      z0019_2 2026-04-30 06:03:23.786959
2   10003    PREGO  BT12   100    60      z0019_2 2026-04-30 06:03:23.786959
6   10004    SERRA  BT50   100   200      z0019_2 2026-04-30 06:04:56.726600
7   10005  MACHADO  BT50   100   100      z0019_2 2026-04-30 06:04:56.726600
8   10003    PREGO  BT12   100    60      z0019_2 2026-04-30 06:04:56.726600
12  10004    SERRA  BT50   100   200      z0019_2 2026-04-30 06:09:20.125918
13  10005  MACHADO  BT50   100   100      z0019_2 2026-04-30 06:09:20.125918
14  10003    PREGO  BT12   100    60      z0019_2 2026-04-30 06:09:20.125918
15  10004    SERRA  BT50   100   200      z0019_2 2026-04-30 06:13:30.850271

In [13]:
df = con.execute("""
                SELECT * 
                FROM bronze_z0019
                ORDER BY data_ingestao DESC
                """).fetchdf()
df.head(50)

    NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0   10003     PREGO  BT12   100    60  z0019_2.csv 2026-04-30 06:17:23.532040
1   10005   MACHADO  BT50   100   100  z0019_2.csv 2026-04-30 06:17:23.532040
2   10004     SERRA  BT50   100   200  z0019_2.csv 2026-04-30 06:17:23.532040
3   10003     PREGO  BT10   100    50  z0019_1.csv 2026-04-30 06:16:34.351304
4   10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-04-30 06:16:34.351304
5   10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-04-30 06:16:34.351304
6   10003     PREGO  BT12   100    60      z0019_2 2026-04-30 06:13:30.850271
7   10005   MACHADO  BT50   100   100      z0019_2 2026-04-30 06:13:30.850271
8   10004     SERRA  BT50   100   200      z0019_2 2026-04-30 06:13:30.850271
9   10004     SERRA  BT50   100   200      z0019_2 2026-04-30 06:09:20.125918
10  10005   MACHADO  BT50   100   100      z0019_2 2026-04-30 06:09:20.125918
11  10003     PREGO  BT12   100    60      z0019_2 2026-04-30 06:09:20.125918
12  10005   MACHADO  BT50   100   100      z0019_2 2026-04-30 06:04:56.726600
13  10003     PREGO  BT12   100    60      z0019_2 2026-04-30 06:04:56.726600
14  10004     SERRA  BT50   100   200      z0019_2 2026-04-30 06:04:56.726600
15  10003     PREGO  BT12   100    60      z0019_2 2026-04-30 06:04:56.726600
16  10005   MACHADO  BT50   100   100      z0019_2 2026-04-30 06:04:56.726600
17  10004     SERRA  BT50   100   200      z0019_2 2026-04-30 06:04:56.726600
18  10003     PREGO  BT12   100    60      z0019_2 2026-04-30 06:03:23.786959
19  10003     PREGO  BT12   100    60      z0019_2 2026-04-30 06:03:23.786959
20  10005   MACHADO  BT50   100   100      z0019_2 2026-04-30 06:03:23.786959
21  10004     SERRA  BT50   100   200      z0019_2 2026-04-30 06:03:23.786959
22  10005   MACHADO  BT50   100   100      z0019_2 2026-04-30 06:03:23.786959
23  10004     SERRA  BT50   100   200      z0019_2 2026-04-30 06:03:23.786959

In [20]:
df_1 = con.execute("""
     SELECT * 
    FROM bronze_z0019
    WHERE nome_arquivo = 'z0019_2.csv'
""").fetchdf()
df_1.head(10)

   NATBR    MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50   100   200  z0019_2.csv 2026-04-30 06:17:23.532040
1  10005  MACHADO  BT50   100   100  z0019_2.csv 2026-04-30 06:17:23.532040
2  10003    PREGO  BT12   100    60  z0019_2.csv 2026-04-30 06:17:23.532040

In [15]:
df_2 = con.execute("""
     SELECT * 
    FROM bronze_z0019
    WHERE nome_arquivo = 'z0019_1.csv'
""").fetchdf()
df_2.head(10)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-04-30 06:16:34.351304
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-04-30 06:16:34.351304
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-04-30 06:16:34.351304

In [16]:
df_final = duckdb.sql("""
            SELECT *
            FROM df_1
            UNION ALL
            SELECT * FROM df_2
      """).fetchdf()
df_final.head(10)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10004     SERRA  BT50   100   200  z0019_2.csv 2026-04-30 06:17:23.532040
1  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-04-30 06:17:23.532040
2  10003     PREGO  BT12   100    60  z0019_2.csv 2026-04-30 06:17:23.532040
3  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-04-30 06:16:34.351304
4  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-04-30 06:16:34.351304
5  10003     PREGO  BT10   100    50  z0019_1.csv 2026-04-30 06:16:34.351304

In [17]:
df = con.execute("""
            SELECT * FROM df_final
            ORDER BY data_ingestao
""").fetchdf()
df.head(10)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-04-30 06:16:34.351304
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-04-30 06:16:34.351304
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-04-30 06:16:34.351304
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-04-30 06:17:23.532040
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-04-30 06:17:23.532040
5  10003     PREGO  BT12   100    60  z0019_2.csv 2026-04-30 06:17:23.532040

In [18]:
df = con.execute("""
                SELECT * FROM (
                 SELECT *, ROW_NUMBER() OVER (PARTITION BY NATBR ORDER BY data_ingestao DESC) AS row,
                 FROM df_final
                WHERE data_ingestao >= '2025-06-16')
                WHERE row = 1
""").fetchdf()
df.head(30)

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_arquivo,data_ingestao,row
0,10005,MACHADO,BT50,100,100,z0019_2.csv,2026-04-30 06:17:23.532040,1
1,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2026-04-30 06:16:34.351304,1
2,10003,PREGO,BT12,100,60,z0019_2.csv,2026-04-30 06:17:23.532040,1
3,10004,SERRA,BT50,100,200,z0019_2.csv,2026-04-30 06:17:23.532040,1
4,10002,MARTELO,BT50,100,1500,z0019_1.csv,2026-04-30 06:16:34.351304,1

In [19]:

df_final = df.rename(columns={'NATBR':'id', 
                              'MAKTX':'nm_produto', 
                              'WERKS':'nm_categoria', 
                              'MAINS':'id_fornecedor',
                               'LABST':'vl_preco' })

df_final = df_final.drop(columns=['nome_arquivo', 'data_ingestao', 'row'])

df_final.head(10)

      id nm_produto nm_categoria id_fornecedor vl_preco
0  10005    MACHADO         BT50           100      100
1  10001   PARAFUSO         BT10           100      100
2  10003      PREGO         BT12           100       60
3  10004      SERRA         BT50           100      200
4  10002    MARTELO         BT50           100     1500

In [21]:
df_final.dtypes

id               object
nm_produto       object
nm_categoria     object
id_fornecedor    object
vl_preco         object
dtype: object

In [24]:
df2 = df_final.astype({'id': 'int64',
                       'nm_produto': 'string',
                          'nm_categoria': 'string',
                            'id_fornecedor': 'int64',
                            'vl_preco': 'float64'})
df2.dtypes

id                        int64
nm_produto       string[python]
nm_categoria     string[python]
id_fornecedor             int64
vl_preco                float64
dtype: object

In [25]:
con.execute("""
CREATE TABLE IF NOT EXISTS produtos
(
    id INTEGER,
    nm_produto STRING,
    nm_categoria STRING,
    id_fornecedor INTEGER,
    vl_preco FLOAT
)
            
""")

In [27]:
df_final.head()

      id nm_produto nm_categoria id_fornecedor vl_preco
0  10005    MACHADO         BT50           100      100
1  10001   PARAFUSO         BT10           100      100
2  10003      PREGO         BT12           100       60
3  10004      SERRA         BT50           100      200
4  10002    MARTELO         BT50           100     1500

In [31]:
con.execute("""
INSERT INTO produtos
SELECT * FROM df_final""")

In [32]:
df_resultado = con.execute("""select * from produtos""").fetchdf() 
df_resultado.head()

      id nm_produto nm_categoria  id_fornecedor  vl_preco
0  10005    MACHADO         BT50            100     100.0
1  10001   PARAFUSO         BT10            100     100.0
2  10003      PREGO         BT12            100      60.0
3  10004      SERRA         BT50            100     200.0
4  10002    MARTELO         BT50            100    1500.0

In [33]:
con.close()