In [1]:
import duckdb

In [2]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [3]:
df = con.execute("""SELECT * FROM produtos""").fetchdf()
df.head()

      id nm_produto nm_categoria  id_fornecedor  vl_preco
0  10005    MACHADO         BT50            100     100.0
1  10001   PARAFUSO         BT10            100     100.0
2  10003      PREGO         BT12            100      60.0
3  10004      SERRA         BT50            100     200.0
4  10002    MARTELO         BT50            100    1500.0

In [5]:
df2 = df.drop(columns=['nm_categoria', 'id_fornecedor'])
df2.head()

      id nm_produto  vl_preco
0  10005    MACHADO     100.0
1  10001   PARAFUSO     100.0
2  10003      PREGO      60.0
3  10004      SERRA     200.0
4  10002    MARTELO    1500.0

In [6]:
df2.dtypes

id              int32
nm_produto     object
vl_preco      float32
dtype: object

In [8]:
con.execute("""
            CREATE TABLE IF NOT EXISTS dim_produtos (
                id_produto INTEGER,
                nm_produto string,
                vl_preco float
            )
""")

In [11]:
con.execute("""
INSERT INTO dim_produtos
SELECT * FROM df2""")

In [12]:
df_dim = con.execute(""" SELECT * FROM dim_produtos""").fetchdf()
df_dim.head()

   id_produto nm_produto  vl_preco
0       10005    MACHADO     100.0
1       10001   PARAFUSO     100.0
2       10003      PREGO      60.0
3       10004      SERRA     200.0
4       10002    MARTELO    1500.0